# Generated by Django 2.2.27 on 2025-10-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_add_is_subscribed_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, help_text='When the subscription expires', null=True, verbose_name='Subscription End Date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, help_text='When the subscription started', null=True, verbose_name='Subscription Start Date'),
        ),
    ]
